[template]
src = "newrelic.tmpl"
dest = "/etc/apache2/conf-available/newrelic.conf"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

keys = [
    "/config"
]

reload_cmd = "/etc/init.d/apache2 restart"
