[template]
src = "newrelic.tmpl"
dest = "/etc/php5/apache2/conf.d/newrelic.ini"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

keys = [
    "/config"
]

reload_cmd = "/etc/init.d/apache2 restart"
