[template]
src = "wiki-secrets.tmpl"
dest = "/etc/nubis-config/%%PROJECT%%.php"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

keys = [
    "/config"
]

#reload_cmd = "/etc/init.d/apache2 restart"
