[template]
src = "wiki.mozilla.org.tmpl"
dest = "/etc/nubis-config/wiki.mozilla.org.secrets"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

keys = [
    "/config"
]

#reload_cmd = "/etc/init.d/apache2 restart"
